# The file that stores the MOTD that is displayed at the top of the chat screen on login
chat-motd:
   enabled: true
   file: chat-motd.txt

# Customise the message that is displayed when a Player connects to the Proxy
# You can set different messages per Group
join-messages:
  enabled: true
  default: '&f[&a+&f] &a%displayName% &fhas joined'
  groups:
    staff: '&f[&a+&f] &a%displayName% &fhas joined, &6respect the staff!'

# Customise the message that is displayed when a Player disconnects from the Proxy
# You can set different messages per Group
quit-messages:
  enabled: true
  default: '&f[&c-&f] &c%displayName% &fhas joined'

# Messages can be broadcast in chat on a loop
auto_messages:
  enabled: false
  delay: 600 # delay between messages in seconds
  prefix: '&dAnnouncement&f: &c'
  messages:
  - 'This is an auto message'
  - 'This is another auto message &awith different formatting'
  - '&eYou can add as many of these as you like and Bungee will keep broadcasting them at the delay you set'
  - '&bYou can use some tokens in these as well, £2the number of players online is %onlinePlayerCount%'

commands:
  /colours:
    file: cmd/colours.txt
    aliases:
    - /colour
    - /colors
    - /color
  /ping:
    file: cmd/ping.txt

discord_chat_relay:
  enabled: false
  bot_token: ''
  herochat_delimiter: '&f: '

  # Customise the message that is displayed when a Player connects to the Proxy
  # You can set different messages per Group
  join-messages:
    enabled: true
    default: '%displayName% has joined'
    groups:
      staff: '%displayName% has joined, respect the staff!'

  # Customise the message that is displayed when a Player disconnects from the Proxy
  # You can set different messages per Group
  quit-messages:
    enabled: true
    default: '%displayName% has left'

  main_herochat_channel: Global
  herochat_channels:
    # Each section represents a Herochat channel and which Discord channel chat should be relayed between
    Global:
      enabled: false
      webhook_url: https://discordapp.com/api/webhooks/...
      discord_channel_id: 123456789
