# The file that stores the MOTD that is displayed at the top of the chat screen on login
chat-motd:
   enabled: true
   file: chat-motd.txt

# Customise the message that is displayed when a Player connects to the Proxy
# You can set different messages per Group
join-messages:
  enabled: true
  default: '&f[&a+&f] &a%displayName% &fhas joined'
  groups:
    staff: '&f[&a+&f] &a%displayName% &fhas joined, &6respect the staff!'

# Customise the message that is displayed when a Player disconnects from the Proxy
# You can set different messages per Group
quit-messages:
  enabled: true
  default: '&f[&c-&f] &c%displayName% &fhas joined'

# Messages can be broadcast in chat on a loop
auto_messages:
  enabled: false
  delay: 600 # delay between messages in seconds
  prefix: '&dAnnouncement&f: &c'
  messages:
  - 'This is an auto message'
  - 'This is another auto message &awith different formatting'
  - '&eYou can add as many of these as you like and Bungee will keep broadcasting them at the delay you set'
  - '&bYou can use some tokens in these as well, £2the number of players online is %onlinePlayerCount%'

commands:
  /colours:
    file: cmd/colours.txt
    aliases:
    - /colour
    - /colors
    - /color
  /ping:
    file: cmd/ping.txt

mysql:
   host: localhost
   port: 3306
   database: enhancedchat
   user: mc
   password:

custom_tokens:
  enabled: false
  tokens:
     nick:
        aliases: [nickname, name, displayname]
        players_enabled: true
        groups_enabled: false

chat:
  enabled: false
  private_messaging:
    message_format: '&c[%fromDisplayName% -> %toDisplayName%] &f%message%'
    me_format: '&7&ome&c'
  defaults:
    formatting:
      player_normal: '&b#%chShortName% %displayName%&f: %message%'
      player_emote: '&b#%chShortName% &e* %displayName% %message%'
      discord_normal: '&b#%chShortName% #Discord %displayName%&f: %message%'
  discord_integration:
    enabled: false
    bot_token: ''
  channels:
    General:
      enabled: true
      shortName: G
      discord:
        webhook_url: https://discordapp.com/api/webhooks/...
        channel_id: 123456789
    Staff:
      enabled: true
      shortName: S
      discord:
        webhook_url: https://discordapp.com/api/webhooks/...
        discord_channel_id: 123456789
      formatting:
        plyaer_normal: '&6#%chShortName% %displayName%&f: &6%message%'
        player_emote: '&6#%chShortName% &6* %displayName% %message%'
        discord_normal: '&6#%chShortName% #Discord %displayName%&f: &6%message%'

discord_status_messages:
  message_channel: General

  # Customise the message that is displayed when a Player connects to the Proxy
  # You can set different messages per Group
  join-messages:
    enabled: true
    default: '%displayName% has joined'
    groups:
      staff: '%displayName% has joined, respect the staff!'

  # Customise the message that is displayed when a Player disconnects from the Proxy
  # You can set different messages per Group
  quit-messages:
    enabled: true
    default: '%displayName% has left'
